//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kevya.Dialogs.Main.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kevya.Dialogs.Main.Resources.MainStrings", typeof(MainStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, let&apos;s start again. How can I help you today?.
        /// </summary>
        public static string CANCELLED {
            get {
                return ResourceManager.GetString("CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for contacting Kevya.
        /// </summary>
        public static string COMPLETED {
            get {
                return ResourceManager.GetString("COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could you please try to rephrase the question? Using different words can sometimes help..
        /// </summary>
        public static string CONFUSED {
            get {
                return ResourceManager.GetString("CONFUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, it looks like something went wrong..
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;messages&quot;:
        ///	[
        ///		{&quot;message&quot;:&quot;Hello {username}! I am Kevya Virtual Assistant. Ask me any question related to following services and I will be happy to assist you&quot;},
        ///{&quot;message&quot;:&quot;Hello {username}! and thanks for trying this experience! I am a Virtual Assistant, always eager to learn new ways to support you better.
        ///You can always type &apos;help&apos; in the chat window to visualize a summary of my current capabilities. You can cancel a process/conversation at any time by typing &apos;Cancel&apos; or &apos;Exit&apos;.
        ///So, how can I he [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GREETING {
            get {
                return ResourceManager.GetString("GREETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey!.
        /// </summary>
        public static string GREETING_WITH_NAME {
            get {
                return ResourceManager.GetString("GREETING_WITH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • I am a Virtual Assistant and I am continuously in training to enhance my skills.
        ///Currently I can help you by answering inquiries related to IT Internal Policies, providing support for Frequently Asked IT Questions, Opening and Providing Status Updates for Request and Incident Tickets.
        ///• 
        ///You can ask me questions such as &apos;Can I get a status update on an open ticket?&apos; or &apos;What is the desktop replacement policy&apos; and even ask me to help you with desktop issues by saying &apos;My computer is slow&apos;.
        /// 
        ///• You can [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HELP_TEXT {
            get {
                return ResourceManager.GetString("HELP_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kevya Virtual Assistant Help.
        /// </summary>
        public static string HELP_TITLE {
            get {
                return ResourceManager.GetString("HELP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am Kevya, a Virtual Assistant. I can help you with Ticket Creation, Ticket Status, IT Policy Documents, KB Articles and announcements. You can ask me things like &apos;Help me with my ticket status&apos;, &apos;How to add people or group to outlook etc.&apos; You can cancel or exit any flow by typing  &apos;Cancel&apos; or &apos;Exit&apos; command..
        /// </summary>
        public static string INTRO_TEXT {
            get {
                return ResourceManager.GetString("INTRO_TEXT", resourceCulture);
            }
        }
    }
}
